# Written by Zoran
# Sep 2, 2024
# Modified by David
# Dec, 2025

Metadata:
  siteID: UQAM_1
  estYear: 2024 
  lat: 46.1645
  long: -72.685
  TimeZoneHour: -5
  northOffset: 285
  
Processing:
  ThirdStage:
    Fluxes:
      # Names of flux variables as they come in from second stage
      # Putting NULL will remove the flux from consideration
      H: H
      LE: LE
      NEE: FC
      FCH4: FCH4
    JS_Moving_Z:
      Run: True
    Papale_Spike_Removal:
      Run: True
    Storage_Correction: 
      Run: False
    REddyProc:
      Run: TRUE
      vars_in:
        NEE: NEE
        LE: LE
        H: H
        FCH4: FCH4
        Rg: SW_IN_1_1_1
        Tair: TA_1_1_1
        VPD: VPD_1_1_1
        Ustar: USTAR
        season: season
      MDSGapFill:
        basic:
          - Rg
          - Tair
          - VPD
      Flux_Partitioning:
        # Turn flux partitioning calculations off to reduce third stage run time for diagnosing errors.
        # Turn flux partitioning calculations off if GPP and Reco are not wanted.
        Run: True


