Database:
  Paths:
    # All paths assumed to be relative to db_root/YYYY/SiteID/ e.g., C:/Users/User/Database/YYYY/SiteID/
    # (see by "Biomet.net/R/database_functions/db_root.R")
    SecondStage: Clean/SecondStage
    ThirdStage: Clean/ThirdStage
    ThirdStage_Default: Clean/ThirdStage_Default_Ustar
    ThirdStage_Advanced: Clean/ThirdStage_Full_Ustar_Uncertainty
    FirstStage:
      Met:
        raw: Met
        clean: Met/clean
      Flux:
        raw: Flux
        clean: Flux/clean
      Manual: 
        raw: Met/Manual
        clean: Met/clean
      ECCC:
        # Station IDs see: _ECCC_Station_List.csv
        raw: ECCC/STN_ID
        clean: Met/clean
  Timestamp: 
    name: clean_tv
    dtype: float64
    precision: 8
    base: 719529
    base_unit: D
  Traces:
    dtype: float32
    precision: 4
Processing:
  ThirdStage:
    Met_Gap_Filling:
      Linear_Interpolation:
        maxgap: 3
        Fill_Vars: TA_1_1_1,RH_1_1_1,VPD_1_1_1
    Storage:
      Apply_Correction: True
      Terms:
        # Will be named acceding to the key, calculated as the sum of the nested key/value pair
        # Gives option to rename flux (e.g., NEE) or just "overwrite"
        # Default behavior is to apply storage correction, but can be "turned off" in site-specific configs
        # If not applied, will still copy/re-name according to nested key values, because for example, REddyProc expects NEE
        NEE:
          FC: SC
        FCH4:
          FCH4: SCH4
        H:
          H: SH
        LE:
          LE: SLE
    REddyProc:
      Ustar_filtering:
        # Keep "run_defaults" as True to run "fast" ustar filtering
        # If run_defaults != True, conduct "full_uncertainty" 
        run_defaults: True
        default_uncertainty:
        # Default to calculate U05, U50, & U95
          samples: 100
          min: 0.05
          max: 0.095
          steps: 3 
        # EProc$sEstimateUstarScenarios(nSample = samples, probs = seq(min_quantile,max_quantile,length.out = steps))
        # See Appendix B5 Wutzler (2018)
        full_uncertainty:
          samples: 200
          min: 0.025
          max: 0.0975
          steps: 39 
      vars_in:
        # Variables to feed to REddyProc (from second stage)
        # Key is REddyProc name, val is database name 
        # year,doy,and HHMM are autogenerated in script)
        # Any variable listed here 
        NEE: NEE
        LE: LE
        H: H
        FCH4: FCH4
        Rg: SW_IN_1_1_1
        Tair: TA_1_1_1
        rH: RH_1_1_1
        VPD: VPD_1_1_1
        Ustar: USTAR
      # MDS gap filling (will only fill these variables *if* present in "vars_in")
      MDSGapFill:
        UStarScens: NEE,LE,H,FCH4
        basic: Rg,Tair,rH,VPD
        
    AmeriFlux_Names:
      # Copy and rename values to third stage folder
      # Final third stage name is key, intermediary third stage name is value
      GPP_PI_F_NT: GPP_uStar_f
      GPP_PI_F_DT: GPP_DT_uStar
      NEE: NEE_uStar_orig
      NEE_PI_F_MDS: NEE_uStar_f
      LE: LE_uStar_orig
      LE_PI_F_MDS: LE_uStar_f
      H: H_uStar_orig
      H_PI_F_MDS: H_uStar_f
      FCH4: FCH4_uStar_orig
      FCH4_PI_F_MDS: FCH4_uStar_f
      Reco_PI_F_NT: Reco_uStar
      Reco_PI_F_DT: Reco_DT_uStar
      # MDS Gap-filled Met Data > should the have a qualifier?
      TA_1_1_1: TA_1_1_1_f
      RH_1_1_1: RH_1_1_1_f
      VPD_1_1_1: VPD_1_1_1_f

    RF_GapFilling:
      # Specify the interval for re-training RF models
      retrain_every_n_months: 1
      # Example showing how configuration could be setup.  Not ideal set of inputs
      # Lots of pending optimizations to be made to RF approach 
      # Example set of predictors (NOT OPTIMIZED!!!!!!!) 
      # Variables with an _f at the end have been gapfilled using MDS in REddyProc
      # Could expand to do MDS gap filling on all necessary inputs ...
      # Or work out our own gap-filling procedures for met/sub surface variables
      Models:
        # Each key corresponds to a model, key corresponds to name of filled variable
        # When saved as the model output, the variable will be appended with a tag
        # e.g., FCH4_RF_f (gap filled w/ random forest) and FCH4_RF_fall (modelled w/ random forest)
        FCH4_PI_F_RF:
          # Full name of the Ustar filtered ReddyProc Variable (cleanest trace) to train model
          var_dep: FCH4
          Predictors: SW_IN_1_1_1,TA_1_1_1,VPD_1_1_1
        NEE_PI_F_RF:
          # Fill the ReddyProc UStar Filtered Variable
          var_dep: NEE
          Predictors: SW_IN_1_1_1,TA_1_1_1,VPD_1_1_1
        H_PI_F_RF:
          # Fill the ReddyProc UStar Filtered Variable
          var_dep: H
          Predictors: SW_IN_1_1_1,TA_1_1_1,VPD_1_1_1
        LE_PI_F_RF:
          # Fill the ReddyProc UStar Filtered Variable
          var_dep: LE
          Predictors: SW_IN_1_1_1,TA_1_1_1,VPD_1_1_1

  FirstStage:
    DependencyTags:
      tag_EC_Vars:
        tag_LowFreq: >
          CO2_MIXING_RATIO
          H2O_MIXING_RATIO
          CH4_MIXING_RATIO
          T_SONIC
        tag_HighFreq:
          tag_LI7X00:
            tag_CO2: >
              FC
              SC
              co2_var
              un_co2_flux
              w_co2_cov
            tag_H2O: >
              LE
              SLE
              h2o_flux
              ET
              un_h2o_flux
              un_LE
              h2o_var
              w_h2o_cov
              h2o_strg
          tag_LI770: >
            FCH4
            SFCH4
            ch4_var
            un_ch4_flux
            w_ch4_cov
          tag_CSAT3: >
            u_mean
            u_unrot
            u_var
            u_rot
            v_mean
            v_unrot
            v_var
            v_rot
            w_mean
            w_unrot
            w_var
            w_rot
            wind_speed
            WS_MAX
            ts
            ts_var,
            H
            w_ts_cov
            SH
            un_H
            USTAR
            TKE
            TAU
            T_SONIC
