[nFiles,nHHours]=fr_HydrologyEXO3_database('Z:\uqam-site\Sites\MCGILL_1\Hydrology\*.csv', ...
                                 'Z:\uqam-site\Database\log\MCGILL_1_Hydrology_progressList.mat','Z:\uqam-site\Database\yyyy\MCGILL_1\Hydrology');
%%
[nFiles,nHHours]=fr_HydrologyEXO3_database('Z:\uqam-site\Sites\UQAM_2\Hydrology\*.csv', ...
                                 'Z:\uqam-site\Database\log\UQAM_2_Hydrology_progressList.mat','Z:\uqam-site\Database\yyyy\UQAM_2\Hydrology');